from enum import Enum


class FoundAt(Enum):
    NONE = 1
    ENTRANCE = 2
    ALCHEMY = 3
    LABORATORY = 4
    MARBLE_GALLERY = 5
    CURSED_PRISON = 6
    OUTER_WALL = 7
    LONG_LIBRARY = 8
    UNDERGROUND_CAVERNS = 9
    ROYAL_CHAPEL = 10
    CASTLE_KEEP = 11
    UNDERGROUND_GARDEN = 12
    OLROXS_QUARTERS = 13
    COLOSSEUM = 14
    ABANDONED_MINE = 15
    CATACOMBS = 16
    CLOCK_TOWER = 17
    MASTER_OF_THE_CASTLE = 18
    REVERSE_KEEP = 19
    REVERSE_CLOCK_TOWER = 20
    REVERSE_OUTER_WALL = 21
    FORBIDDEN_LIBRARY = 22
    BLACK_MARBLE_GALLERY = 23
    DEATH_WINGS_LAIR = 24
    REVERSE_COLOSSEUM = 25
    ANTI_CHAPEL = 26
    REVERSE_CAVERNS = 27
    REVERSE_CURSED_PRISON = 28
    NECROMANCY_LABORATORY = 29
    REVERSE_ENTRANCE = 30
    HELL_GARDEN = 31
    CAVE = 32
    FLOATING_CATACOMBS = 33
    FINAL_SHOWDOWN = 34

    def __str__(self):
        return self.name
